---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This analysis includes following steps:

- [Preprocessing](01-preprocessing.html)
- [Quality control](02-quality_control.html)
    - [SampleQC](02.1-SampleQC.html)
- [Filtering](03-filtering.html)

Analysis of the two NSC samples:

- [NSC clustering](NSC-1-clustering.html)
- [NSC annotation](NSC-2-annotation.html)

Integrated analysis of all 6 samples:

- [Clustering](04-clustering.html)
    - [Cell cycle](04.1-cell_cycle.html)
- [Annotation](05-annotation.html)

Integration with Lam et al. 2019.
Neuroepithelial stem (NES) cells:

- [Integration](Lam-01-NSC_integration.html)
- [Cluster comparison](Lam-02-NSC_annotation.html)

Integration with Kanton et al. 2019.
Cerebral organoids:

- [Clustering](organoid-01-clustering.html)
- [DR without integration](organoid-02-integration.html)
    - [Cluster abundances](organoid-03-cluster_analysis.html)
- [Group integration](organoid-04-group_integration.html)
    - [Cluster abundances](organoid-05-group_integration_cluster_analysis.html)
- [Stage integration](organoid-04-stage_integration.html)
    - [Cluster abundances](organoid-05-stage_integration_cluster_analysis.html)
    
Integration with Conos:

- [Preprocessing of sce object](organoid-06-1-prepare-sce.html)
- [Conos integration](organoid-06-conos-analysis.html)
- [Conos group integration](organoid-06-group-integration-conos-analysis.html)


We additionally sequenced neural cultures at 223 days and performed a TDP-43 overexpression experiment (at 96 days):

- [Preprocessing](TDP-01-preprocessing.html)
- [Quality control](TDP-02-quality_control.html)
- [Filtering](TDP-03-filtering.html)
- [Clustering (no integration)](TDP-04-clustering.html)

We quantified the transcript encoded by the plasmid and the endogenous TDP-43 with alevin and include the counts in the analysis.

- [Filtering and TDP-43 HA expression](TDP-05-00-filtering-plasmid-QC.html)
- [Clustering (no integration)](TDP-05-plasmid_expression.html)
- [Cluster analysis](TDP-06-cluster_analysis.html)
    - [Analysis of cluster 12 (TDP-HA positive)](TDP-07-cluster_12.html)
    - [STMN2 read coverage in cluster 12](TDP-07-01-STMN2_expression.html)
    - [Cluster 12 marker expression in ALS brain RNA-seq](TDP-07-02-Prudencio_marker_expression.html)
    - [Cluster 12 marker expression in sorted neuronal nuclei from FTD-ALS patients](TDP-07-03-Liu_sorted_nuclei_marker_expression.html")
    
We combine the TDP-HA samples with the D96 samples as controls (all samples are D96):

- [Clustering (no integration)](TDP-08-00-clustering-HA-D96.html)
- [Expression changes](TDP-08-01-HA-D96-expression-changes.html)
    - [Comparison of DE genes with HEK cell TDP-43 targets](TDP-08-02-TDP_target_genes.html)

TDP-HA samples and all other samples: 

- [Clustering (no integration)](TDP-08-clustering-timeline-HA.html)

We combine the D223 samples with the P22, D56 and D96 samples:

- [Clustering (no integration)](06-clustering-all-timepoints.html)
- [Cluster analysis](07-cluster-analysis-all-timepoints.html)

We also integrate the organoid samples:

- [Clustering](timepoints-01-organoid-integration.html)
    - [Cluster analysis](timepoints-02-cluster-analysis.html)



Test experiment for demultiplexing with hashtag oligos

- [Preprocessing and quality control](CH-test-01-preprocessing.html)
- [Transgene expression and clustering](CH-test-02-transgene-expression.html)
- [Cluster analysis](CH-test-03-cluster-analysis.html)
